services:
  tp_sms:
    image: ghcr.io/sitscholl/tplinksms:latest
    container_name: tplinksms
    environment:
      - TZ=Europe/Rome
    ports:
      - "7772:8080"
    volumes:
      - ./config/:/app/config/
    restart: unless-stopped